# Generated by Django 5.1.2 on 2024-11-05 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='burned_calories',
            field=models.PositiveIntegerField(blank=True, help_text='Approximate calories burned during the workout', null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='workout',
            name='equipment_needed',
            field=models.TextField(blank=True, help_text='List of equipment required for the workout, if any'),
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength'), ('flexibility', 'Flexibility'), ('balance', 'Balance'), ('endurance', 'Endurance')], default='cardio', max_length=20),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration_minutes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
