# Generated by Django 5.1.2 on 2024-11-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_workout_equipment_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='equipment_needed',
            field=models.TextField(blank=True, default='no', help_text='List of equipment required for the workout, if any'),
        ),
    ]
