# Generated by Django 5.1.2 on 2024-11-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_alter_workout_burned_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='equipment_needed',
            field=models.TextField(default='no', help_text="enter a equpment if it's required"),
        ),
    ]
